### ISSUE TITLE
System.IO.IOException while uploading package to Design Automation

### ISSUE THREAD

**Issue by talebi** [Autodesk-Forge/forge-api-dotnet-design.automation#54]
I'm using the code found on below link to create an AppBundle and upload a package via Design Automation api for Revit:
[link](https://github.com/Autodesk-Forge/forge-countdeletewalls-revit/blob/346888edcd4b1f8f5b03fa7c482defafff7525ea/WebApp/Controllers/DesignAutomationController.cs#L173)

But I got an exception in the response as per below:
```
{System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|182_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)}
```

strange thing is that using the postman collection in tutorials [here](https://aps.autodesk.com/en/docs/design-automation/v3/tutorials/revit/about_this_tutorial/) works with no error whatsoever. 

Could you please help me figure out whats causing the issue?

**Comment by szilvaa** [comment]
The [call that fails](https://github.com/Autodesk-Forge/forge-countdeletewalls-revit/blob/346888edcd4b1f8f5b03fa7c482defafff7525ea/WebApp/Controllers/DesignAutomationController.cs#L173) does not use this SDK at all. It uses the [RestClient](https://restsharp.dev/) to upload to S3. I recommend that you consult the authors of the sample.

**Comment by talebia** [comment]
so how to use this sdk instead of restclient to make that happen? is there a code sample I can use?

**Comment by talebi** [comment]
never mind found it:
`_da4RevitClient.UploadAppBundleBits(newAppVersion.UploadParameters, packageZipPath)`
